### ISSUE TITLE
promising results

### ISSUE THREAD

**Issue by zhang-jian** [barronalex/Tacotron#4]
Thank you, very promising result.
Dataset: arctic only
Parameters: everything is default
Training time: 14 hours

![untitled](https://user-images.githubusercontent.com/3985740/27171201-a9b7d55e-51a8-11e7-831e-f728ca042b1c.png)

[individualAudio.zip](https://github.com/barronalex/Tacotron/files/1076931/individualAudio.zip)

**Comment by YisenWang** [comment]
@barronalex @zhang-jian Have you run into this issues when using arctic?

Traceback (most recent call last):
  File "train.py", line 117, in <module>
    train(model, config)
  File "train.py", line 28, in train
    batch_inputs = data_input.build_dataset(sess, inputs)
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/data_input.py", line 26, in build_dataset
    dataset = tf.contrib.data.Dataset.from_tensor_slices(placeholders)
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 473, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 907, in __init__
    for i, t in enumerate(nest.flatten(tensors))
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 610, in convert_to_tensor
    as_ref=False)
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 921, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/data1/home/yisenwang/TTS/tacotron2/Tacotron/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 863, in _autopacking_helper
    "%s to %s (Tensor is: %r)" % (elem.dtype, dtype, elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float32'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'Placeholder_2:0' shape=(1131, 64, 5125) dtype=float32>)

**Comment by auzxb** [comment]
Please update your Tensorflow to tensorflow_gpu-1.2.0/tensorflow_cpu-1.2.0 @YisenWang

**Comment by YisenWang** [comment]
It is already 1.2.0.

**Comment by YisenWang** [comment]
I have fixed this one when I update tensorflow from 1.2.0rc2 to 1.2.0

**Comment by jacksmithe** [comment]
@zhang-jian For some reason I can't hear your audio samples. Maybe the files are buggie?

**Comment by zhang-jian** [comment]
@jacksmithe https://www.dropbox.com/s/845j6yll7uxf0bt/individualAudio.wav?dl=0

**Comment by onyedikilo** [comment]
@zhang-jian is this sample generated through test.py or train.py?

**Comment by mrelich** [comment]
Anyone else having difficulty getting consistent output during training and from test.py?  I am finding test.py gives garbage while output during training is getting better after many epochs.
